# permissions for end users to view secrettemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrettemplate-viewer-role
rules:
- apiGroups:
  - keymanagement.ibm
  resources:
  - secrettemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keymanagement.ibm
  resources:
  - secrettemplates/status
  verbs:
  - get
