# permissions for end users to edit secrettemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrettemplate-editor-role
rules:
- apiGroups:
  - keymanagement.ibm
  resources:
  - secrettemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keymanagement.ibm
  resources:
  - secrettemplates/status
  verbs:
  - get
